### ISSUE TITLE
Touch event is not fire on list item after search

### ISSUE THREAD

**Issue by dyaacov** [localz/react-native-searchbar#25] opened 2017-04-20 19:26 UTC
Hi All,
I'm missing events when the search is active.

One example:
1. Search bar and a simple **Button** in a vertical view
2. Start search
3. Click the button  - No click event, the only event is that the search bar lost focus.

Any idea?

Thanks
Dekel

**Comment by daveols** [comment] 2017-04-25 14:11
@dyaacov I believe you are after the `onSubmitEditing` callback. Pass a function to this, then you can `this.searchBar.getValue()` to get the text that the user has inputted. 

Let me know if this helps.

**Comment by dyaacov** [comment] 2017-04-25 14:16
That's not the case.
The searchbar performs search and filter my contact list. that's ok.
Now, I want to select one of the contacts... here is the problem, one click
is not enough, the first click only move the focus from the searchbar to
the contact list item, only second click selects the contact.

**Comment by daveols** [comment] 2017-04-25 15:09
@dyaacov oh, I see.

This may be due to the way you've implemented your contact list. Can you reproduce the issue with the minimum amount of code and post it here?

**Comment by dyaacov** [comment] 2017-04-26 08:00
In your example, searchbar is on the same component as the list.
In my app, I implemented a generic navigation bar that holds the searchbar.
It is only a guess, I'll test it and update

**Comment by dyaacov** [comment] 2017-05-02 17:35
Found the answer:
In my ListView, I added keyboardShouldPersistTaps="handled" to solve my
issue.

**Comment by daveols** [comment] 2017-05-03 02:15
@dyaacov thanks for the update! I'll close this issue.

**Closed by daveols** 2017-05-03 02:15 UTC
