### ISSUE TITLE
Integration with ReactNavigation

### ISSUE THREAD

**Issue by whimsicaldreamer** [localz/react-native-searchbar#45] opened 2017-10-19 19:29 UTC
How can we integrate it with ReactNavigation as the searchbar goes after React navigation header and not over it.?

**Comment by VittoriDavide** [comment] 2017-10-24 14:50
Try setting it before starting your navigation, for example I did this in a past project 

`
<View>
 <SearchBar
                    ref={(ref) => this.searchBar = ref}
                    placeholder="Search"
                    handleSearch={this.search}
                    data={[]}
                    handleResults={this._handleResults}
                    onBack={() => this.closeSearch()}
                    backgroundColor="#339999"
                    textColor="white"
                    selectionColor="white"
                    iconColor="white"
                />

                <MainNavigator/>

</View>`

**Comment by Unforgiven-wanda** [comment] 2017-12-17 10:54
@VittoriDavide But how would you call the ref from the children then?
Passing it down the `MainNavigator` seems like a mouthful

**Comment by daveols** [comment] 2017-12-19 05:15
@Unforgiven-wanda you could create a higher order component `WithSearchBar` to wrap your screens in, which handles the SearchBar state and passes a prop down to the wrapped component (your screen) which enables you to activate the search bar.

**Comment by daveols** [comment] 2018-06-04 12:57
Closing as this is a dupe of #13

**Closed by daveols** 2018-06-04 12:57 UTC
